### ISSUE TITLE
Die Dateihosting-Site ist ungültig

### ISSUE THREAD

**Issue by kronn** [iNaD/ds-mediatheken#10]
Bei der Installation der Version 0.1.2 bekomme ich den Fehler "Die Dateihosting-Site ist ungültig". 
Die Installation von 0.1.1 funktioniert einwandfrei.

Ich habe eine DS215j mit DSM 6.1.5-15254 und DownloadStation 3.8.7-3490.

**Comment by iNaD** [comment]
Dann scheint mein Script für Linux nicht ganz richtig zu funktionieren. Habe die aktuelle Version noch mal unter Windows fertig gemacht. Nun sollte es funktionieren: https://github.com/iNaD/ds-mediatheken/releases/download/v0.1.2/mediathek.host

**Comment by kronn** [comment]
Jetzt wurde das Update ohne Beanstandungen akzeptiert. 

Ich sehe eigentlich auch keinen Fehler im build.sh. tar sollte mit -czf "Create Zipped File" sauber funktionieren. Möchtest du hierbei Hilfe haben?

Da das ursprüngliche Problem behoben ist (DANKE!), schließe ich das Issue hier mal...

**Comment by iNaD** [comment]
Ich habe inzwischen vermutlich den Fehler gefunden 😄

In der Windows Version erstelle ich erst ein Tar mit dem Namen `mediathek` und dann wird es gzipped als `mediathek.host`. Somit enhält `mediathek.host` eine Tar Datei, während eine `tar.gz` einen Ordner enthalten würde.

Die neue Variante sollte somit das richtige Ergebnis erzielen:

```sh
tar -C ../src -cvf mediathek .
gzip --suffix=.host mediathek
```

**Comment by kronn** [comment]
ja, stimmt. Normalerweise ist das Verhalten von tar so auch besser. Nur für die engstirnige DiskStation wieder mal nicht :-D
