### ISSUE TITLE
Current release seems broken in my DS (DSM 6.1.5-15254)

### ISSUE THREAD

**Issue by manfredwurz** [iNaD/ds-mediatheken#13]
I uploaded the currently reased mediathek.host file, and when trying do download something (in my case, from ARD), the plugin wasn't trigged.

By doing a tail -f /var/log/messages on my DS, I found out, that the mediathek.host file was extracted by the DS in flat structure and the sub directories utils and mediatheken where empty.

Moving the files to the right place, sorting them into the subdirectory manually, fixed the problem.

Though, I let you know.

Thanks for the great work you did! Very much appreciated!

Manfred

**Comment by iNaD** [comment]
Which version of Download Station are you using?

**Comment by iNaD** [comment]
Closing for no response. If this error still occurs feel free to open a new issue
