### ISSUE TITLE
Quality of download from ARD mediathek

### ISSUE THREAD

**Issue by slh24** [iNaD/ds-mediatheken#17]
Videos aus der ARD Mediathek werden bei mir in niedrigster Qualität heruntergeladen. Beispielsweise 90 Minuten Tatort mit Dateigröße um 100 MB. Mit der Version v0.1.2 hatte ich das Problem nicht.

Diskstation: DS216j
DSM: 6.2.1
ds-mediatheken: v0.2.0

**Comment by iNaD** [comment]
Hi, ich werde mir das mal ansehen

**Comment by iNaD** [comment]
Wurde in #18 behoben. Die ARD hat wohl die Struktur der Qualitäten etwas verändert.
Werde heute noch eine neue Version veröffentlichen mit den Änderungen 😃

**Comment by iNaD** [comment]
So neue Version habe ich erstellt: https://github.com/iNaD/ds-mediatheken/releases/latest

**Comment by slh24** [comment]
Hallo Daniel, danke für das schnelle Update :) 
Damit funktioniert es bei mir jetzt aber leider gar nicht mehr. Es wird nur die Website mit Dateiname "Video" heruntergeladen.

**Comment by iNaD** [comment]
Kannst du mir den Link mitteilen, welchen du nutzt?

**Comment by slh24** [comment]
Zum Test habe ich folgenden verwendet:
https://www.ardmediathek.de/tv/Tatort/Blut/Das-Erste/Video?bcastId=602916&documentId=57207056

Version 0.2.1 ist installiert.

**Comment by iNaD** [comment]
Hi, ich habe gerade wohl den Fehler gefunden 🙈 
Könntest du die angehängte Version mal ausprobieren? Sollte als `0.3.0` auftauchen.
Habe leider gerade keine Synology zum ausprobieren, ob das mit dem Namespace so in der INFO Datei ausreicht.
Das ZIP-Archiv vorher entpacken. Github erlaubt in Kommentaren nur ein paar Dateitypen.
[mediathek.host.zip](https://github.com/iNaD/ds-mediatheken/files/2531462/mediathek.host.zip)

**Comment by slh24** [comment]
Habe die Version gerade getestet, damit funktioniert der Download problemlos 😃 Mir ist noch aufgefallen, dass jetzt eine höhere Qualität (1280x720) heruntergeladen wird als zuvor (960x540).

Vielen Dank für deine Arbeit 👍

**Comment by iNaD** [comment]
Perfekt, dann werde ich die Version gleich veröffentlichen
