### ISSUE TITLE
Support für neue ARD Mediathek

### ISSUE THREAD

**Issue by iNaD** [iNaD/ds-mediatheken#22]
Es gab ein großes Update für die ARD Mediathek. 

Beispielvideo:
https://www.ardmediathek.de/ard/player/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Zlcm5zZWhmaWxtZSBpbSBlcnN0ZW4vMjMxNjU3OWMtNTZmNi00NTdlLWJkYzktNzcwMDdjZjNmZjAw/das-blaue-vom-himmel

Früher befand sich in der URL ein Parameter `documentId`, dieser existiert mit dem neuen Update nicht mehr.

**Comment by slh24** [comment]
Hallo Daniel, 

durchsuch mal den Quelltext nach `contentID`. Damit habe ich die ID zu deinem Beispielvideo gerade gefunden: `"contentId":58472888`

Und @mediathekview hat offensichtlich auch zu kämpfen: https://github.com/mediathekview/MServer/issues/401

Viele Grüße

**Comment by iNaD** [comment]
Ich habe nur eben gelesen, dass die Mediathek jetzt in der neuen Version draußen ist und nur mal kurz getestet. Aber die von dir gefundene ID scheint mit der alten API noch zu funktionieren. Dann wäre das Problem ja schnell behoben.

**Comment by iNaD** [comment]
Die Anpassungen (auch um den Titel zu generieren) habe ich im MR #23 durchgeführt.
Stichprobenartig habe ich auch den NDR & WDR über die ARD Mediathek ausprobiert und diese haben auch funktioniert. Werde dann demnächst die neue Version veröffentlichen.

**Comment by segro21** [comment]
der mediathek link lädt jetzt wieder in 0.40 aber nur die schlechteste Auflösung. Muss man noch was einstellen?
