### ISSUE TITLE
arte.tv: "Die Wege des Herrn" - only one language

### ISSUE THREAD

**Issue by chri2** [iNaD/ds-mediatheken#24]
I successfully downloaded the following URL:
https://www.arte.tv/de/videos/062202-001-A/die-wege-des-herrn-staffel-1-1-10/

Content is offered with various languages and subtitles. Couldn't find out how to download the german synchronized version.

**Comment by iNaD** [comment]
Hi, please try this version:
[mediathek.host.zip](https://github.com/iNaD/ds-mediatheken/files/2687786/mediathek.host.zip)

Don't forget to unzip it first. It should prefer the german source.

**Comment by chri2** [comment]
Thanks :), download with german track confirmed. Genreal question would be, how to let the user select?

**Comment by iNaD** [comment]
Currently the only way to change the language is to change the url from `de` to `fr` or using the language chooser on the arte homepage.

The new version v0.4.1 now contains a fix for your problem.
