### ISSUE TITLE
reduzierte Auflösung

### ISSUE THREAD

**Issue by Trevor75** [iNaD/ds-mediatheken#26]
Hallo iNaD,
vorab vielen Dank für dieses sehr gelungene DS Plugin, welches den Funktionsumfang weiter bereichert!

Leider werden mit der aktuellen Version 0.4.1 die Video nur in einer reduzierte Auflösung von 852x480 statt 1280x720 herunter geladen (getestet mit mehreren Video von ZDF und 3Sat).
Innerhalb der Mediatheken spielen die Video in voller Auflösung.

Vielen Dank für einen Fix vorab!

**Comment by iNaD** [comment]
Hi Trevor75,

vielen Dank für dein Lob & Feedback.
Ich habe einige Videos vom ZDF und 3Sat ausprobiert und immer die höchst verfügbare Qualität erhalten. Das kann natürlich auch nur Zufall sein.
Um dir helfen zu können, würde ich Links zu betroffenen Videos benötigen.

**Comment by Trevor75** [comment]
Vielen dank für die schnelle Antwort. Hier ein Link zu einem Beispielt-Video:
http://www.3sat.de/mediathek/?mode=play&obj=77564
Startet in der Mediathek in 1280x720 - Download ist dagegen 852x480.

**Comment by iNaD** [comment]
Hi, habe gesehen dass die Qualität nicht in allen berücksichtigten Gruppen vorhanden ist.
Habe mal probehalber eine Regel raus genommen, wodurch ich die bessere Qualität erhalten habe.

Probiere mal [v0.4.2](https://github.com/iNaD/ds-mediatheken/releases/tag/v0.4.2)
Für ZDF habe ich auf die Schnelle leider kein Video mit solch einer Qualität gefunden, um dort den Fehler zu beheben.

**Comment by Trevor75** [comment]
Hi, funzt nun prima für 3Sat!
Hier ein Video von ZDF, das ebenfalls nur in der kleinen Auflösung ist:
https://www.zdf.de/filme/der-fernsehfilm-der-woche/extraklasse-100.html

**Comment by iNaD** [comment]
Vielen Dank für den Link. Leider liefert die ZDF Api maximal die zweit höchste Auflösung zurück.
Nur die Playlisten für den Player enthalten die höhere Auflösung. Die sind allerdings aufgesplittet und müssten von einem extra Tool zusammengefügt werden. Da lässt sich wohl vorerst nichts machen.
