### ISSUE TITLE
ERROR: INSTALL

### ISSUE THREAD

**Issue by OliB73** [iNaD/ds-mediatheken#27]
HI !

I ALWAYS GET THE FOLLOWING ERROR MESSAGE WHEN ADD IN THE HOST FILE "VORGANG FEHLGESCHLAGEN" - WHAT DO I NEED TO DO DIFFERENT ?

THX,
OLIVER

**Comment by iNaD** [comment]
Hi Oliver,

do you have problems installing the Host or with a specific episode?
If you provide an url to an episode I can take a look at it.

**Comment by OliB73** [comment]
Hi Daniel,

I downloaded the .host file 

https://github.com/iNaD/ds-mediatheken/releases/download/v0.4.2/mediathek.host

and tried to install it to my DS Videostation

Auf den Reiter Dateihosting wechseln und auf Hinzufügen klicken

But I only get an error message.

Von meinem iPad gesendet

Oliver

**Comment by iNaD** [comment]
Sorry for the late feedback.
Are you sure you opened Videostation? This is a Plugin for Download Station.

**Comment by iNaD** [comment]
Closing because of no response for months
