### ISSUE TITLE
"Sendung mit der Maus" RSS not working

### ISSUE THREAD

**Issue by patrickhartung** [iNaD/ds-mediatheken#28]
I try to download "Sendung mit der Maus" via RSS from the ARD Mediathek. RSS can be added successfully (http://mediathek.daserste.de/Die-Sendung-mit-der-Maus/Sendung?documentId=1458&topRessort&bcastId=1458&rss=true) if I select a episode for download, only Video1 with a few KB will be downloaded.

Download TerraX episodes works however. Am I doing something wrong?

Thanks for your support.

**Comment by iNaD** [comment]
Hi,

thank you for the report. It seems like some parts of the ARD Mediathek are still using the old format. I released a [new version](https://github.com/iNaD/ds-mediatheken/releases/tag/v0.4.3) v0.4.3 which addresses this.

**Comment by patrickhartung** [comment]
Hi,
perfect, now all my tested videos are downloading!
Thanks!

Good night.
