### ISSUE TITLE
Download from ARTE mediathek not working

### ISSUE THREAD

**Issue by slh24** [iNaD/ds-mediatheken#29]
Hallo Daniel,

mir ist gerade aufgefallen, dass ich aus der ARTE-Mediathek keine Videos mehr herunterladen kann. Ein Beispiel: https://www.arte.tv/de/videos/086138-029-A/re-wege-aus-dem-stau/

Statt dem Video wird dann die HTML-Datei heruntergeladen. Ich habe es mit v0.4.3 und v0.4.2 versucht.

Viele Grüße, Simon

**Comment by iNaD** [comment]
Vielen Dank für den Hinweis Simon. [v0.4.4](https://github.com/iNaD/ds-mediatheken/releases/latest) behebt das Problem

**Comment by slh24** [comment]
Bei mir funktioniert es mit der v0.4.4. Vielen Dank für deine Arbeit :)
