### ISSUE TITLE
ARD Videos von außerhalb der Mediathek

### ISSUE THREAD

**Issue by iNaD** [iNaD/ds-mediatheken#3]
Original Issue: https://github.com/iNaD/download-station-ardmediathek/issues/5

Möglichkeit, um Videos von der restlichen ARD Homepage herunterzuladen.

> Bei Eingabe von:
> http://www.daserste.de/unterhaltung/film/filme-im-ersten/videos/der-zuerich-krimi-borcherts-abrechnung-102.html (Der Zürich-Krimi: Borcherts Abrechnung 05.05.16 | 88:37 Min.)
> wird bei mir nur der Html-Text der Seite heruntergeladen.
> 
> Bisher lief es gut. Habe die neuste Version v0.6b (15.05.2015 22:34) der Datei ardmediathek.host
> installiert, leider ohne Erfolg beim Herunterladen des o.g. Films.
> 
> Meine DS: DS216play, DSM 6.0-7321 Update 6
> 
> Mache ich etwas falsch? Oder woran liegt es?
> 
> Danke und Gruß, HJ-Meyer

> Habe leider die anderen Kommentare erst nach meinem obigen Kommentar zu Gesicht bekommen. Die Lösung war, dass ich die falsche Adresse für das Video genommen habe. Offenbar verwendet die ARD mehrere Adressen, über die man den Film ansehen kann. Bei http://mediathek.daserste.de/Filme-im-Ersten/Der-Z%C3%BCrich-Krimi-Borcherts-Abrechnung/Das-Erste/Video?documentId=35154402&topRessort&bcastId=1933898 beginnt der Download der mp4-Datei sofort.
> 
> Danke und Gruß, HJ-Meyer

> es gehen halt nur die Links aus der Mediathek, nicht die von der normalen ARD Seite.

**Comment by HJMeyer** [comment]
Danke!

**Comment by iNaD** [comment]
Ich schließe hier mal, da ich leider aktuell keinen Link mit Video finden konnte, welcher nicht auf eine der Mediatheken (ARD, Arte o.ä.) verlinkt. Sollte jemand wieder einen solchen Link finden, so kann gerne ein neues Issue erstellt werden 😄
