### ISSUE TITLE
Dowload von 3Sat

### ISSUE THREAD

**Issue by ghost** [iNaD/ds-mediatheken#30]
Wie erbeten ein Ticket für einen nicht funktionierenden Link. 
Der Link: https://www.3sat.de/film/spielfilm/reykjavik-rotterdam-toedliche-lieferung-100.html
Die Station: Syn DS 218+, 2 * 4 TB, 10 GB Ram.

**Comment by iNaD** [comment]
Sollte behoben sein mit [v0.5.0](https://github.com/iNaD/ds-mediatheken/releases/latest)
