### ISSUE TITLE
Video download not working with v0.5.0

### ISSUE THREAD

**Issue by slh24** [iNaD/ds-mediatheken#31]
Mit v0.5.0 ist ein Download von Videos (alle Mediatheken) nicht mehr möglich.

Ursache:
Reihenfolge der includes in _SynoFileHostingMediathek.php_, da die _DreiSat_-Klasse nun von der _ZDF_-Klasse abhängig ist.

**Comment by iNaD** [comment]
Hi, vielen Dank für deine Meldung und den Fix. Ich versuche mir das die nächsten Tage anzusehen und einen neuen Release zu machen. Entschuldige die späte Antwort.

**Comment by iNaD** [comment]
Habe deine Änderung gemerged und eine [neue Version](https://github.com/iNaD/ds-mediatheken/releases/latest) veröffentlicht.
