### ISSUE TITLE
donwloard file nicht nutzbar

### ISSUE THREAD

**Issue by hubertAD** [iNaD/ds-mediatheken#33]
Hallo,

ich habe das add on wie beschrieben in die download application von Synology eingefügt und die URL aus den Mediotheken kopiert. . Leider wird keine mp4-Datei erzeugt. Angezeigt wird eine Datei ohne bekannte Endung, <100 KB. Warum?

Hubert

**Comment by iNaD** [comment]
Hallo Hubert,

ich bräuchte da eine Info, um welche Mediathek es sich handelt und am Besten mit dem Link, welchen du versucht hast über die Synology herunterzuladen.

**Comment by hubertAD** [comment]
Hallo Daniel,

zunächst, ich habe alle Host-Dateien, also auch BR und co integriert. Bei der Maus könnte es sein, dass diese die Links tatsächlich nicht mehr funktionieren, da nur eine vorherige Sendung vorgehalten wird. Ich hatte mir Links gespeichert und wollt die in einem Rutsch nachholen:

https://www.br.de/mediathek/video/bergauf-bergab-20102019-der-koenigsweg-auf-den-mont-blanc-av:5d78e65ee364e90013e0ca6d
https://www.br.de/mediathek/video/bergauf-bergab-22092019-mit-dem-gleitschirm-ueber-alle-berge-av:5d5ab0daac0b3c001a444eeb
https://www.wdrmaus.de/aktuelle-sendung/vorwoche.php5
https://www.ardmediathek.de/swr/player/Y3JpZDovL3N3ci5kZS9hZXgvbzExNzExNzQ/vom-bockerl-in-bayern-in-den-wilden-westen

Grüsse
Hubert

**Comment by teilzeitutopist** [comment]
Ich habe den Link der ARD Mediathek von Hubert gerade ausprobiert, weil ich auch Probleme beim Downloads habe: Aber der funktioniert bei mir problemlos. @hubertAD: Es gibt nur eine Host-Datei für alle Mediatheken zusammen, die du in der Download-Station einrichten musst, nicht mehrere: https://github.com/iNaD/ds-mediatheken/releases/download/v0.5.1/mediathek.host 

Zu meinem Problem: Ich kann wiederum nichts mehr von arte herunterladen, z.B.:
https://www.arte.tv/de/videos/065779-000-A/1000-arten-regen-zu-beschreiben/

Besten Gruß
teilzeitutopist

**Comment by hubertAD** [comment]
Da findet sich aber z.B. kein BR oder SWR

"Unterstützt folgende Mediatheken:
3sat (3sat.de)
ARD (ardmediathek.de, mediathek.daserste.de)
Arte (arte.tv)
KiKa (kika.de)
MDR (mdr.de)
NDR (ndr.de)
RBB (mediathek.rbb-online.de)
WDR (wdr.de/mediathek, one.ard.de/mediathek)
ZDF Mediathek (zdf.de)"

**Comment by iNaD** [comment]
Hi Hubert,

genau für BR, SWR & ORF müssen noch die alten Host-Dateien genutzt werden (falls diese noch funktionieren). Alle anderen Mediatheken laufen über diese eine neue Host-Datei.

Ich muss mal schauen wann ich Zeit finde, um mir die Probleme anzusehen und z.B. den BR auch in DS Mediatheken aufzunehmen.

@hubertAD Bitte achte beim Antworten der E-Mails darauf, dass deine E-Mail Signatur auch auf GitHub veröffentlicht wird. Ich habe diese bei beiden deiner Kommentare entfernt und auch den Bearbeitungsverlauf, um deine Daten zu schützen.

**Comment by iNaD** [comment]
Ich schließe dieses Ticket erstmal.
PR #35 behebt Probleme mit der ARD.
BR, SWR & ORF müssen vorerst mit den alten Hosts geladen werden (insofern diese noch funktionieren).
