### ISSUE TITLE
kein ARD mediathek video download, wenn Hörfassung verfügbar

### ISSUE THREAD

**Issue by tpatzig** [iNaD/ds-mediatheken#34]
Beispiel: https://www.ardmediathek.de/daserste/player/Y3JpZDovL2Rhc2Vyc3RlLmRlL2tpbmRlcmZpbG1lLXVuZC1raW5kZXJkb2t1cy9lMjMyZjVkNC05MWNlLTRhN2MtOGU3OS03MmFmMDZhMjdlYTM/pinocchio

Die Hörfassung kann dagegen ohne Probleme geladen werden.

**Comment by iNaD** [comment]
Vielen Dank für deine Meldung. Ich werde mal sehen wann ich Zeit finde. Ich bin mir nicht sicher, ob die ARD nun auch auf die Lösung vom ZDF setzt. Falls ja, dann sollte ich das hoffentlich zeitig lösen können :)

**Comment by tpatzig** [comment]
https://github.com/iNaD/ds-mediatheken/pull/35 fixed das für mich.
Ich habe damit nun diverse ARD mediathek title erfolgreich geladen.
Neben dem regex für die richtige media stream URL, war das title setzen auch kaputt. Hier wurde immer `audiothek.mp4` gesetzt. Das geht damit nun auch wieder.

**Comment by tpatzig** [comment]
https://github.com/iNaD/ds-mediatheken/issues/33 ist ziemlich sicher das gleiche Problem. Die kleinen files ohne suffix, sind einfach die pageSource. 
Er findet die stream URL wegen des falschen regex nicht und lädt nur die player Seite runter.

**Comment by iNaD** [comment]
Vielen Dank für deinen Fix :)
Habe eine neue Version released: https://github.com/iNaD/ds-mediatheken/releases/latest
