### ISSUE TITLE
Auflösung

### ISSUE THREAD

**Issue by HickHub20** [iNaD/ds-mediatheken#37]
Hallo, leider ist die Auflösung der Videos nur 852x480 statt HD obwohl das Video in HD vorliegt. Getestet mit 3sat und der neuen ARD mediathek.
Danke!

**Comment by iNaD** [comment]
Vielen Dank für deine Rückmeldung :) Konkrete Links erleichtern mir immer die Fehlersuche.
Ich schaue mal, wann ich Zeit finde das Problem zu beheben.

**Comment by iNaD** [comment]
Ich habe mal geschaut und konnte folgende Folgen in Full HD herunterladen:
[Babylon Berlin - Folge 1](https://www.ardmediathek.de/ard/player/Y3JpZDovL2Rhc2Vyc3RlLmRlL2JhYnlsb24tYmVybGluLzYwMzk5MTBlLTBhZDAtNDg1Ni04OWRkLWQxODdjZmZiNmMxYw/folge-1)
[Der Zürich-Krimi: Borchert und die tödliche Falle](https://www.ardmediathek.de/ard/player/Y3JpZDovL2Rhc2Vyc3RlLmRlL2tyaW1pcy1pbS1lcnN0ZW4vYWQ5M2Q5ZWItYTk4Ny00MmI3LTllOGMtOGJiNmIxOWU5ZTkx/borchert-und-die-toedliche-falle)

Die URLs von Little Britain enthalten z.B. gar keine Angabe über die Qualität, so dass ich mich auf die Angaben der Schnittstelle verlassen muss: [Little Britain (S1/E1)](https://www.ardmediathek.de/ard/player/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTc3OWE2MTYxLTZlMTktNGRjOS05OWQyLTQ2M2ZhNjE4Njc3ZQ/)

Hier kann ich also erst weiter nachforschen, wenn du mir eine URL zu einer Folge gibst, welche nicht in höchster Qualität heruntergeladen wird.

Nichtsdestotrotz habe ich eine Anpassung bei der Qualitätserkennung vorgenommen, welche allgemein eine bessere Trefferquote haben sollte. Teste es gerne mit [v0.6.1](https://github.com/iNaD/ds-mediatheken/releases/latest) und teile mir gerne die URLs mit, solltest du weiterhin Probleme haben :)

**Comment by HickHub20** [comment]
Hallo Daniel,

danke für das Update.

Ich habe dies mal geprüft und es wird leider nur die kleine Auflösung geladen:

https://www.3sat.de/kultur/pop-around-the-clock/coldplay-104.html 

Viele Grüße

**Comment by iNaD** [comment]
Das Problem ist hier, dass über die API höhere Auflösungen nur als Stream angeboten werden.
Leider sind nicht alle Videos der Mediatheken als einzelne MP4 Datei in HD verfügbar. In diesem Fall ist die höchst verfügbare Auflösung leider wirklich 852x480.
An dieser Stelle ist die Download Station leider etwas eingeschränkt, ansonsten könnte man alle Stream Dateien herunterladen und zu einer Datei zusammenführen. Dann hätte man die HD Auflösung vom Webplayer.

Da kann ich dir leider nicht weiterhelfen. Du könntest es mit JDownloader oder Mediathekview probieren, ob die bessere Auflösungen herunterladen können. Ich glaube zumindest JDownloader besitzt die Fähigkeit die Streams zu einer Datei zusammenzusetzen.
