### ISSUE TITLE
zdf audiodescription

### ISSUE THREAD

**Issue by segro21** [iNaD/ds-mediatheken#38]
Hi, vielen Dank für das super Plugin. Ich habe beim zdf häufiger das Problem, dass mir die Datei incl. Audiodescription heruntergeladen wird, statt des std. audio-streams. Das kann man im Nachhinein auch leider nicht deaktivieren über audiospuren. z.B. https://www.zdf.de/serien/bad-banks/schoene-neue-welt-138.html hat jemadn ne idee, wie man das fixen kann?

**Comment by iNaD** [comment]
Das Problem sollte mit der [neuesten Version](https://github.com/iNaD/ds-mediatheken/releases/latest) behoben sein.

**Comment by segro21** [comment]
super, Danke!
