### ISSUE TITLE
Mediathek downloads doesnt work on all videos

### ISSUE THREAD

**Issue by Left-Handed-Cat** [iNaD/ds-mediatheken#39]
I've tried to download several videos from ARD Mediathek. Unfortunately only 1 in 3, that i have tested, downloaded successfully, 2 ended with timeout error. See Screenshot:

![image](https://user-images.githubusercontent.com/69760981/90338021-ed9a3580-dfe6-11ea-9a88-edff1479f5c4.png)

**Comment by iNaD** [comment]
Thank you for reporting. Currently I'm a bit out of time, because of my newborns.
If anyone creates a pull request fixing this bug, I would gladly publish a new version.

**Comment by iNaD** [comment]
I would close this in favor of #40, because the failed downloads have been from the BR mediathek
