### ISSUE TITLE
BR Mediathek funktioniert nicht

### ISSUE THREAD

**Issue by millerb-by** [iNaD/ds-mediatheken#40]
Hallo, 
zunächst vielen dank für die einfache Möglichkeit über die Mediatheken zu downloaden.

ZDF & WDR funktionieren wunderbar. 
BR Mediathek jedoch nicht.
Lädt Datei runter, ist jedoch keine mp4. Eventuell hat BR hier eine Sperre eingebaut.

Gruß
Millerb

**Comment by iNaD** [comment]
Vielen Dank für die Meldung. Ich habe aktuell durch Nachwuchs leider kaum Zeit und kann hier noch nicht sagen wann ich mir das ansehen könnte.
Sollte jemand anders einen Pull Request machen, um das Problem zu beheben so würde ich zwischendurch eine neue Version erstellen.

**Comment by iNaD** [comment]
Hi, ich arbeite gerade in #44 daran alle Mediatheken wieder lauffähig zu bekommen. Ich hoffe noch kommende Woche ein Release mit den Fixes machen zu können.

**Comment by iNaD** [comment]
Die neue Version sollte das Problem lösen: https://github.com/iNaD/ds-mediatheken/releases/latest

Sollte weiterhin ein Problem bestehen, dann öffne dieses Issue gerne wieder oder erstelle ein neues.
