### ISSUE TITLE
White Sands from ardmediathek.de not downloading

### ISSUE THREAD

**Issue by tich78** [iNaD/ds-mediatheken#42]
Link for first episode:
https://www.ardmediathek.de/video/white-sands-strand-der-geheimnisse/white-sands-strand-der-geheimnisse-s01-e00/ndr/Y3JpZDovL25kci5kZS9lMjlhMDY3Ny1kNjViLTQ3ZTYtOTY2NS04YzlmYjkwZTA3MDA/

**Comment by iNaD** [comment]
Sorry for the late response. I'm still very busy with work and private stuff. I hope to update the extension over the christmas holidays, so the downloads will work again.

**Comment by iNaD** [comment]
I'm currently fixing this in #44. I hope for a release soon.

**Comment by iNaD** [comment]
The latest release should fix this: https://github.com/iNaD/ds-mediatheken/releases/latest

Feel free to re-open this issue or create a new one if a problem occurs.
