### ISSUE TITLE
Wie installiere ich die ds-mediathek, in der DSM 7.2.1-69057 Update 5

### ISSUE THREAD

**Issue by LeonBisai** [iNaD/ds-mediatheken#50]
In dieser Version gibt es den Diskstation Managers leider nicht.
Gibt es trotzdem eine Möglichkeit die Mediathek zu installieren?

**Comment by iNaD** [comment]
Also ich habe die DSM 7.2.1-69057 Update 4 aktuell am laufen und habe Download Station. Was hast du denn bisher versucht?
